logging:
  level: debug

welcome-message: true

# Web server
web:
  host: "0.0.0.0"
  port: 8484

## Connector modules
connectors:
 
  websocket:
    bot-name: "kabot"

## Skill modules
skills:

  ## API.AI (https://github.com/opsdroid/skill-apiai)
  apiai: {}

  ## Last seen (https://github.com/opsdroid/skill-seen)
  seen: {}

  ## Dance (https://github.com/opsdroid/skill-dance)
  dance: {}

  ## Loud noises (https://github.com/opsdroid/skill-loudnoises)
  loudnoises: {}
